# Generated by Django 5.1.6 on 2025-02-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='telephone',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefono'),
        ),
    ]
