# Generated by Django 5.1.6 on 2025-02-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_staff_account_is_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Es Estudiante'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Es Docente'),
        ),
    ]
