# Generated by Django 5.1.6 on 2025-02-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='telephone',
            field=models.CharField(max_length=15, verbose_name='Telefono'),
        ),
    ]
