# Generated by Django 5.1.6 on 2025-03-13 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_first_name_alter_account_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='account',
            name='is_researcher',
            field=models.BooleanField(default=False, verbose_name='Es Investigador'),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Carnet de Estudiante'),
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50, verbose_name='Especialidad')),
                ('researcher_id', models.CharField(max_length=50, unique=True, verbose_name='Carnet de Docente')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
