# Generated by Django 5.1.6 on 2025-02-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Descripcion'),
        ),
    ]
