# Generated by Django 5.1.6 on 2025-03-17 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_is_researcher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('department', models.CharField(max_length=50, verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='career',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='specialization',
        ),
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_mentor',
            field=models.BooleanField(default=False, verbose_name='Es Mentor'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_researcher',
            field=models.BooleanField(default=False, verbose_name='Es Investigador'),
        ),
        migrations.AddField(
            model_name='account',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.career'),
        ),
        migrations.AddField(
            model_name='career',
            name='knowledge_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.knowledgearea'),
        ),
    ]
